all:
	make -C share all
	make -C fms all
	make -C plm all
	make -C pfm all

test:
	make -C fms test
	make -C plm test
	make -C pfm test

clean:
	make -C share clean
	make -C fms clean
	make -C plm clean
	make -C pfm clean
